SilverStripe\Assets\Image:
  extensions:
    - ImageExtension
    - AfricaDataObjectExtension
SilverStripe\AssetAdmin\Controller\AssetAdmin:
  extensions:
    - AssetAdminExtension
AudioPiece:
  extensions:
    - AfricaDataObjectExtension
VideoPiece:
  extensions:
    - AfricaDataObjectExtension
Chapter:
  extensions:
    - AfricaDataObjectExtension
Country:
  extensions:
    - AfricaDataObjectExtension
Essay:
  extensions:
    - AfricaDataObjectExtension
People:
  extensions:
    - AfricaDataObjectExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension
